name: CI/CD pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.3

      - name: Run Tests
        run: go test -v ./...

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Fly CLI
        run: |
          curl -L https://github.com/superfly/flyctl/releases/latest/download/flyctl_linux_amd64.tar.gz | tar xzv
          sudo mv flyctl /usr/local/bin/flyctl
          flyctl version

      - name: Deploy to Fly
        run: flyctl deploy -i flyio/criptology
